### ISSUE TITLE
NaN issue in DR_discriminator.py file

### ISSUE THREAD

**Issue by Santhanalakshmimano** [LiDan456/Multivariate-Anomaly-Detection-for-Time-Series-Data-with-GANs#2]
While testing KDD dataset, in DR_discriminator.py file I am getting nan values for reconstruction error, and G_samples are also nan.. Do anybody knows why this happens ?

**Comment by sathyapatel** [comment]
Hi Santhanalakshmi,
I am facing the same issue on kdd99 test data.. Heuristic sigma is 0 and reconstruction error is NAN..Please let me know, if you solved this issue

**Comment by Santhanalakshmimano** [comment]
Hi Sathyapatel,
The issue is due to the distance we calculate. Just change the line 
distances = np.sqrt(X_sqnorms.reshape(-1, 1) - 2 * XY + Y_sqnorms.reshape(1, -1)) **to** 
distances = np.sqrt(((X[:, None] - Y[:, :, None]) ** 2).sum(0))

**Comment by Adapter525** [comment]
why you change edistances in this way? thank you

**Comment by Adapter525** [comment]
@Santhanalakshmimano why you change edistances in this way? thank you
